// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGI6yOYkLU14inOe5_WSn6ocaGaPJnFgo',
    appId: '1:937549052951:web:e63bdb6870bd1a4e9db052',
    messagingSenderId: '937549052951',
    projectId: 'crossplatformapp-a7659',
    authDomain: 'crossplatformapp-a7659.firebaseapp.com',
    storageBucket: 'crossplatformapp-a7659.appspot.com',
    measurementId: 'G-L9XG2C1TVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6v_-XLcIgIYcp2PwLX_2A0dGeh-wiYrI',
    appId: '1:937549052951:android:dad87803536b23969db052',
    messagingSenderId: '937549052951',
    projectId: 'crossplatformapp-a7659',
    storageBucket: 'crossplatformapp-a7659.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmlkooXIc_qNepFNY9RBcpGMZLI0jYLhg',
    appId: '1:937549052951:ios:f0730aa8fa3ef5da9db052',
    messagingSenderId: '937549052951',
    projectId: 'crossplatformapp-a7659',
    storageBucket: 'crossplatformapp-a7659.appspot.com',
    iosBundleId: 'com.noesia.crossplatformapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmlkooXIc_qNepFNY9RBcpGMZLI0jYLhg',
    appId: '1:937549052951:ios:24a1073853bf6ed99db052',
    messagingSenderId: '937549052951',
    projectId: 'crossplatformapp-a7659',
    storageBucket: 'crossplatformapp-a7659.appspot.com',
    iosBundleId: 'com.noesia.crossplatformapp.RunnerTests',
  );
}
